var m_CANopenConst = {}

/*	THESE SIZE MUST BE ALIGNED WITH FIRMWARE!!! */

/* 	POWERPC - size in bytes */

m_CANopenConst.POWERPC = {}

m_CANopenConst.POWERPC.SIZEOF_PROCIMG = 8
m_CANopenConst.POWERPC.SIZEOF_PDO_TX_HDLR = 40
m_CANopenConst.POWERPC.SIZEOF_PDO_RX_HDLR = 20
m_CANopenConst.POWERPC.SIZEOF_NMTE_HDLR = 24
m_CANopenConst.POWERPC.SIZEOF_SDO_HDLR = 48
m_CANopenConst.POWERPC.SIZEOF_PRM_HDLR = 12
m_CANopenConst.POWERPC.SIZEOF_COPM_NETLIST_HDLR = 32
m_CANopenConst.POWERPC.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_NO = 16		//	NO HEARTBEAT
m_CANopenConst.POWERPC.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_YES = 28		//	HEARTBEAT SUPPORTED

m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_CAN = 1
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODE = 1
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODE_PADDING = 2		//	padding
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_BOOTTIME = 2
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_BOOTTIME_PADDING = 2	//	padding
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODEGUARDING = 2
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_LTF = 1
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_MANDATORY = 1
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_PARAMS = 2
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_PDORX = 1
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_PDOTX = 1
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODE_HBP = 2
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODE_HBP_PADDING = 2	//	padding
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODE_HBC = 2
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_NODE_HBC_PADDING = 2	//	padding
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_MASTER_HBC = 2
m_CANopenConst.POWERPC.SIZE_COPM_NETLIST_CFG_MASTER_HBC_PADDING = 2	//	padding

m_CANopenConst.POWERPC.BYTE_SIZE = 8
m_CANopenConst.POWERPC.DATA_TYPE = "BYTE"
m_CANopenConst.POWERPC.IS_BIG_ENDIAN = true

/* 	ARM - size in bytes */

m_CANopenConst.ARM = {}

m_CANopenConst.ARM.SIZEOF_PROCIMG = 8
m_CANopenConst.ARM.SIZEOF_PDO_TX_HDLR = 40
m_CANopenConst.ARM.SIZEOF_PDO_RX_HDLR = 20
m_CANopenConst.ARM.SIZEOF_NMTE_HDLR = 24
m_CANopenConst.ARM.SIZEOF_SDO_HDLR = 48
m_CANopenConst.ARM.SIZEOF_PRM_HDLR = 12
m_CANopenConst.ARM.SIZEOF_COPM_NETLIST_HDLR = 32
m_CANopenConst.ARM.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_NO = 12		//	NO HEARTBEAT
m_CANopenConst.ARM.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_YES = 20		//	HEARTBEAT SUPPORTED

m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_CAN = 1
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODE = 1
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODE_PADDING = 0		//	NO padding
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_BOOTTIME = 2
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_BOOTTIME_PADDING = 0	//	NO padding
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODEGUARDING = 2
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_LTF = 1
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_MANDATORY = 1
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_PARAMS = 2
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_PDORX = 1
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_PDOTX = 1
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODE_HBP = 2
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODE_HBP_PADDING = 0	//	NO padding
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODE_HBC = 2
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_NODE_HBC_PADDING = 0	//	NO padding
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_MASTER_HBC = 2
m_CANopenConst.ARM.SIZE_COPM_NETLIST_CFG_MASTER_HBC_PADDING = 2	//	padding

m_CANopenConst.ARM.BYTE_SIZE = 8
m_CANopenConst.ARM.DATA_TYPE = "BYTE"
m_CANopenConst.ARM.IS_BIG_ENDIAN = false

/* 	RENESAS_RX - size in bytes */

m_CANopenConst.RENESAS_RX = {}

m_CANopenConst.RENESAS_RX.SIZEOF_PROCIMG = 8
m_CANopenConst.RENESAS_RX.SIZEOF_PDO_TX_HDLR = 40
m_CANopenConst.RENESAS_RX.SIZEOF_PDO_RX_HDLR = 20
m_CANopenConst.RENESAS_RX.SIZEOF_NMTE_HDLR = 24
m_CANopenConst.RENESAS_RX.SIZEOF_SDO_HDLR = 48
m_CANopenConst.RENESAS_RX.SIZEOF_PRM_HDLR = 12
m_CANopenConst.RENESAS_RX.SIZEOF_COPM_NETLIST_HDLR = 32
m_CANopenConst.RENESAS_RX.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_NO = 12		//	NO HEARTBEAT
m_CANopenConst.RENESAS_RX.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_YES = 20		//	HEARTBEAT SUPPORTED

m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_CAN = 1
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODE = 1
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODE_PADDING = 0		//	NO padding
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_BOOTTIME = 2
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_BOOTTIME_PADDING = 0	//	NO padding
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODEGUARDING = 2
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_LTF = 1
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_MANDATORY = 1
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_PARAMS = 2
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_PDORX = 1
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_PDOTX = 1
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODE_HBP = 2
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODE_HBP_PADDING = 0	//	NO padding
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODE_HBC = 2
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_NODE_HBC_PADDING = 0	//	NO padding
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_MASTER_HBC = 2
m_CANopenConst.RENESAS_RX.SIZE_COPM_NETLIST_CFG_MASTER_HBC_PADDING = 2	//	padding

m_CANopenConst.RENESAS_RX.BYTE_SIZE = 8
m_CANopenConst.RENESAS_RX.DATA_TYPE = "BYTE"
m_CANopenConst.RENESAS_RX.IS_BIG_ENDIAN = false

/* 	TEXAS TMS320 (BIT) - size in word */

m_CANopenConst.TMS320_BIT = {}

m_CANopenConst.TMS320_BIT.SIZEOF_PROCIMG = 4
m_CANopenConst.TMS320_BIT.SIZEOF_PDO_TX_HDLR = 24
m_CANopenConst.TMS320_BIT.SIZEOF_PDO_RX_HDLR = 10
m_CANopenConst.TMS320_BIT.SIZEOF_NMTE_HDLR = 12
m_CANopenConst.TMS320_BIT.SIZEOF_SDO_HDLR = 30
m_CANopenConst.TMS320_BIT.SIZEOF_PRM_HDLR = 8
m_CANopenConst.TMS320_BIT.SIZEOF_COPM_NETLIST_HDLR = 20
m_CANopenConst.TMS320_BIT.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_NO = 9		//	NO HEARTBEAT
m_CANopenConst.TMS320_BIT.SIZEOF_COPM_NETLIST_CFG_HDLR_HB_YES = 13		//	HEARTBEAT SUPPORTED	- da verificare

m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_CAN = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODE = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODE_PADDING = 0		//	NO padding
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_BOOTTIME = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_BOOTTIME_PADDING = 0	//	NO padding
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODEGUARDING = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_LTF = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_MANDATORY = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_PARAMS = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_PDORX = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_PDOTX = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODE_HBP = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODE_HBP_PADDING = 0	//	NO padding
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODE_HBC = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_NODE_HBC_PADDING = 0	//	NO padding
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_MASTER_HBC = 1
m_CANopenConst.TMS320_BIT.SIZE_COPM_NETLIST_CFG_MASTER_HBC_PADDING = 1	//	padding

m_CANopenConst.TMS320_BIT.BYTE_SIZE = 16
m_CANopenConst.TMS320_BIT.DATA_TYPE = "WORD"
m_CANopenConst.TMS320_BIT.IS_BIG_ENDIAN = false
