var m_ModbusRTUMasterConst = {}

/*	THESE SIZE MUST BE ALIGNED WITH FIRMWARE!!! */

/* 	x86 - size in bytes */

m_ModbusRTUMasterConst.x86 = {}

m_ModbusRTUMasterConst.x86.SIZEOF_MSG_QUEUE = 56;
if (MODBUSRTU_MASTER_SWAP_SUPPORTED)
	m_ModbusRTUMasterConst.x86.SIZEOF_MSG_QUEUE += 4;
if (MODBUSRTU_MASTER_INCREMENTAL_MSG_CONFIGURATION && MODBUSRTU_MASTER_ONESHOT_SUPPORTED)
	m_ModbusRTUMasterConst.x86.SIZEOF_MSG_QUEUE += 4;
if (MODBUSRTU_MASTER_INCREMENTAL_MSG_CONFIGURATION && MODBUSRTU_MASTER_INPUTOUTPUTCMD_SUPPORTED)
	m_ModbusRTUMasterConst.x86.SIZEOF_MSG_QUEUE += 4;

m_ModbusRTUMasterConst.x86.SIZEOF_NETLIST = 40;		//	MbMRtuNetList

/* 	ARM - size in bytes */

m_ModbusRTUMasterConst.ARM = {}

m_ModbusRTUMasterConst.ARM.SIZEOF_MSG_QUEUE = 56
if (MODBUSRTU_MASTER_SWAP_SUPPORTED)
	m_ModbusRTUMasterConst.ARM.SIZEOF_MSG_QUEUE += 4;
if (MODBUSRTU_MASTER_INCREMENTAL_MSG_CONFIGURATION && MODBUSRTU_MASTER_ONESHOT_SUPPORTED)
	m_ModbusRTUMasterConst.ARM.SIZEOF_MSG_QUEUE += 4;
if (MODBUSRTU_MASTER_INCREMENTAL_MSG_CONFIGURATION && MODBUSRTU_MASTER_INPUTOUTPUTCMD_SUPPORTED)
	m_ModbusRTUMasterConst.ARM.SIZEOF_MSG_QUEUE += 4;

m_ModbusRTUMasterConst.ARM.SIZEOF_NETLIST = 40;		//	MbMRtuNetList
