//	MODBUSRTU_MASTER_ADDRESSING_MODE_MODBUS if firmware stack is configured as Modbus (default)
//	MODBUSRTU_MASTER_ADDRESSING_MODE_JBUS if firmware stack is configured as Jbus
//	var MODBUSRTU_MASTER_ADDRESSING_MODE = MODBUSRTU_MASTER_ADDRESSING_MODE_MODBUS
//	slaves diagnostic and msg queue are dinamically allocated
//MODBUSRTU_MASTER_DYNAMIC_ALLOCATION_LEV2 = true
//MODBUSRTU_MASTER_SWAP_SUPPORTED = true
//MODBUSRTU_MASTER_INCREMENTAL_MSG_CONFIGURATION = true
//MODBUSRTU_MASTER_ONESHOT_SUPPORTED = true
//MODBUSRTU_MASTER_DYNAMICSLAVEADDRESS_SUPPORTED = true
//MODBUSRTU_MASTER_INPUTOUTPUTCMD_SUPPORTED = true
//MODBUSRTU_SYSMBMRTUNETLIST_BASENAME = "sysMbMRtuNetList"
//MODBUSRTU_SYSMBMRTUNETLIST_TYPENAME = "MbMRtuNetList"
//	specific target architecture settings
MODBUSRTU_MASTER_TARGET_ARCHITECTURE = MODBUSRTU_MASTER_TARGET_x86
