//	MODBUSTCP_MASTER_ADDRESSING_MODE_MODBUS reg addresses entered are modbus addresses
//	MODBUSTCP_MASTER_ADDRESSING_MODE_JBUS reg addresses entered are jbus addresses
//	MODBUSTCP_MASTER_ADDRESSING_MODE = MODBUSTCP_MASTER_ADDRESSING_MODE_MODBUS
//	MODBUSTCP_MASTER_DYNAMICSLAVEADDRESS_SUPPORTED = true

// MODBUSTCP_MASTER_TARGET_ARM = 0	//	default
// MODBUSTCP_MASTER_TARGET_x86 = 1
MODBUSTCP_MASTER_TARGET_ARCHITECTURE = MODBUSTCP_MASTER_TARGET_x86